#############################################################################
# Makefile for building: simulator
# Generated by qmake (3.0) (Qt 5.1.1) on: ? 9? 21 22:26:56 2013
# Project:  simulator.pro
# Template: app
# Command: /home/mackrick/.qt/5.1.1/gcc_64/bin/qmake -o Makefile simulator.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -std=gnu++11 -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../.qt/5.1.1/gcc_64/mkspecs/linux-g++ -I. -I. -Isrc -Isrc/GA -I../../.qt/5.1.1/gcc_64/include -I../../.qt/5.1.1/gcc_64/include/QtWidgets -I../../.qt/5.1.1/gcc_64/include/QtGui -I../../.qt/5.1.1/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/mackrick/.qt/5.1.1/gcc_64 -Wl,-rpath,/home/mackrick/.qt/5.1.1/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/mackrick/.qt/5.1.1/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/mackrick/.qt/5.1.1/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/car.cc \
		src/draw.cc \
		src/land.cc \
		src/main.cc \
		src/navi.cc \
		src/signal.cc \
		src/GA/chromosome.cpp \
		src/GA/clossover.cc \
		src/GA/individual.cpp \
		src/GA/method.cc \
		src/GA/mutate.cc \
		src/GA/population.cc \
		src/GA/selectver3.05.cc moc_draw.cpp
OBJECTS       = car.o \
		draw.o \
		land.o \
		main.o \
		navi.o \
		signal.o \
		chromosome.o \
		clossover.o \
		individual.o \
		method.o \
		mutate.o \
		population.o \
		selectver3.05.o \
		moc_draw.o
DIST          = ../../.qt/5.1.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/unix.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/linux.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/g++-base.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/qconfig.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/qt_config.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/spec_post.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/default_pre.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/unix/default_pre.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/default_post.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/warn_on.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/qt.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/resources.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/moc.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/uic.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/wayland-scanner.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/exceptions.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/yacc.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/lex.prf \
		simulator.pro \
		simulator.pro
QMAKE_TARGET  = simulator
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = simulator


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: simulator.pro ../../.qt/5.1.1/gcc_64/mkspecs/linux-g++/qmake.conf ../../.qt/5.1.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/unix.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/linux.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/g++-base.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/qconfig.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../.qt/5.1.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/qt_config.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/spec_post.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/default_pre.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/unix/default_pre.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/default_post.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/warn_on.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/qt.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/resources.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/moc.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/uic.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/wayland-scanner.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/exceptions.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/yacc.prf \
		../../.qt/5.1.1/gcc_64/mkspecs/features/lex.prf \
		simulator.pro \
		/home/mackrick/.qt/5.1.1/gcc_64/lib/libQt5Widgets.prl \
		/home/mackrick/.qt/5.1.1/gcc_64/lib/libQt5Gui.prl \
		/home/mackrick/.qt/5.1.1/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile simulator.pro
../../.qt/5.1.1/gcc_64/mkspecs/features/spec_pre.prf:
../../.qt/5.1.1/gcc_64/mkspecs/common/shell-unix.conf:
../../.qt/5.1.1/gcc_64/mkspecs/common/unix.conf:
../../.qt/5.1.1/gcc_64/mkspecs/common/linux.conf:
../../.qt/5.1.1/gcc_64/mkspecs/common/gcc-base.conf:
../../.qt/5.1.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../.qt/5.1.1/gcc_64/mkspecs/common/g++-base.conf:
../../.qt/5.1.1/gcc_64/mkspecs/common/g++-unix.conf:
../../.qt/5.1.1/gcc_64/mkspecs/qconfig.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_v8.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../.qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../.qt/5.1.1/gcc_64/mkspecs/features/qt_functions.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/qt_config.prf:
../../.qt/5.1.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../.qt/5.1.1/gcc_64/mkspecs/features/spec_post.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/default_pre.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/unix/default_pre.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/resolve_config.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/default_post.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/warn_on.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/qt.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/resources.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/moc.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/unix/opengl.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/uic.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/unix/thread.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/wayland-scanner.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/exceptions.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/yacc.prf:
../../.qt/5.1.1/gcc_64/mkspecs/features/lex.prf:
simulator.pro:
/home/mackrick/.qt/5.1.1/gcc_64/lib/libQt5Widgets.prl:
/home/mackrick/.qt/5.1.1/gcc_64/lib/libQt5Gui.prl:
/home/mackrick/.qt/5.1.1/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile simulator.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/simulator1.0.0 || mkdir -p .tmp/simulator1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/simulator1.0.0/ && $(COPY_FILE) --parents src/car.h src/draw.h src/land.h src/signal.h src/GA/chromosome.h src/GA/individual.h src/GA/population.h .tmp/simulator1.0.0/ && $(COPY_FILE) --parents src/car.cc src/draw.cc src/land.cc src/main.cc src/navi.cc src/signal.cc src/GA/chromosome.cpp src/GA/clossover.cc src/GA/individual.cpp src/GA/method.cc src/GA/mutate.cc src/GA/population.cc src/GA/selectver3.05.cc .tmp/simulator1.0.0/ && (cd `dirname .tmp/simulator1.0.0` && $(TAR) simulator1.0.0.tar simulator1.0.0 && $(COMPRESS) simulator1.0.0.tar) && $(MOVE) `dirname .tmp/simulator1.0.0`/simulator1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/simulator1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_wayland_server_header_make_all:
compiler_wayland_server_header_clean:
compiler_wayland_client_header_make_all:
compiler_wayland_client_header_clean:
compiler_qtwayland_client_header_make_all:
compiler_qtwayland_client_header_clean:
compiler_qtwayland_server_header_make_all:
compiler_qtwayland_server_header_clean:
compiler_moc_header_make_all: moc_draw.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_draw.cpp
moc_draw.cpp: src/land.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QHash \
		../../.qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QLineF \
		../../.qt/5.1.1/gcc_64/include/QtCore/qline.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QString \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		src/signal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QPointF \
		../../.qt/5.1.1/gcc_64/include/QtCore/QMap \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h \
		src/car.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QRectF \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrect.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsize.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/QWidget \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qwidget.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmargins.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpalette.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qcolor.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qrgb.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdatastream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qregexp.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qbrush.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qmatrix.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpolygon.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qregion.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qtransform.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpainterpath.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qimage.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpixmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qfont.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qfontinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qcursor.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qkeysequence.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qurl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qurlquery.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfile.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfiledevice.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qvector2d.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qtouchdevice.h \
		src/GA/population.h \
		src/GA/individual.h \
		src/GA/chromosome.h \
		src/draw.h
	/home/mackrick/.qt/5.1.1/gcc_64/bin/moc $(DEFINES) $(INCPATH) src/draw.h -o moc_draw.cpp

compiler_wayland_code_make_all:
compiler_wayland_code_clean:
compiler_qtwayland_client_code_make_all:
compiler_qtwayland_client_code_clean:
compiler_qtwayland_server_code_make_all:
compiler_qtwayland_server_code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

car.o: src/car.cc src/car.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QPointF \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QRectF \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrect.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsize.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QDebug \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o car.o src/car.cc

draw.o: src/draw.cc src/draw.h \
		src/land.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QHash \
		../../.qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QLineF \
		../../.qt/5.1.1/gcc_64/include/QtCore/qline.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QString \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		src/signal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QPointF \
		../../.qt/5.1.1/gcc_64/include/QtCore/QMap \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h \
		src/car.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QRectF \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrect.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsize.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/QWidget \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qwidget.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmargins.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpalette.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qcolor.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qrgb.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdatastream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qregexp.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qbrush.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qmatrix.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpolygon.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qregion.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qtransform.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpainterpath.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qimage.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpixmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qfont.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qfontinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qcursor.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qkeysequence.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qurl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qurlquery.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfile.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfiledevice.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qvector2d.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qtouchdevice.h \
		src/GA/population.h \
		src/GA/individual.h \
		src/GA/chromosome.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/QPainter \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpainter.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qtextoption.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpen.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QTimer \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtimer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasictimer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QDebug \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o draw.o src/draw.cc

land.o: src/land.cc src/land.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QHash \
		../../.qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QLineF \
		../../.qt/5.1.1/gcc_64/include/QtCore/qline.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QString \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		src/signal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QPointF \
		../../.qt/5.1.1/gcc_64/include/QtCore/QMap \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QFile \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfile.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfiledevice.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QIODevice \
		../../.qt/5.1.1/gcc_64/include/QtCore/QDebug \
		../../.qt/5.1.1/gcc_64/include/QtCore/QList \
		../../.qt/5.1.1/gcc_64/include/QtCore/QTextStream \
		../../.qt/5.1.1/gcc_64/include/QtCore/QStringList \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdatastream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qregexp.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QtGlobal
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o land.o src/land.cc

main.o: src/main.cc ../../.qt/5.1.1/gcc_64/include/QtWidgets/QWidget \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qwidget.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmargins.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrect.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsize.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpalette.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qcolor.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qrgb.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdatastream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qregexp.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qbrush.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qmatrix.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpolygon.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qregion.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qline.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qtransform.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpainterpath.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qimage.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpixmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qfont.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qfontinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qcursor.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qkeysequence.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qurl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qurlquery.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfile.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfiledevice.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qvector2d.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qtouchdevice.h \
		src/draw.h \
		src/land.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/QHash \
		../../.qt/5.1.1/gcc_64/include/QtCore/QLineF \
		../../.qt/5.1.1/gcc_64/include/QtCore/QString \
		src/signal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QPointF \
		../../.qt/5.1.1/gcc_64/include/QtCore/QMap \
		src/car.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QRectF \
		src/GA/population.h \
		src/GA/individual.h \
		src/GA/chromosome.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/QApplication \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qapplication.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qeventloop.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qguiapplication.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qinputmethod.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/QPushButton \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qpushbutton.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qicon.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/QDial \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qdial.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qabstractslider.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/QLCDNumber \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qlcdnumber.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qframe.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbitarray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cc

navi.o: src/navi.cc src/land.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QHash \
		../../.qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QLineF \
		../../.qt/5.1.1/gcc_64/include/QtCore/qline.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QString \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		src/signal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QPointF \
		../../.qt/5.1.1/gcc_64/include/QtCore/QMap \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h \
		src/draw.h \
		src/car.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QRectF \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrect.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsize.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/QWidget \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qwidget.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmargins.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpalette.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qcolor.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qrgb.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdatastream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qregexp.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qbrush.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qmatrix.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpolygon.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qregion.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qtransform.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpainterpath.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qimage.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qpixmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qfont.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qfontinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qcursor.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qkeysequence.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qurl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qurlquery.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfile.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfiledevice.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qvector2d.h \
		../../.qt/5.1.1/gcc_64/include/QtGui/qtouchdevice.h \
		src/GA/population.h \
		src/GA/individual.h \
		src/GA/chromosome.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmath.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o navi.o src/navi.cc

signal.o: src/signal.cc src/signal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QPointF \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QMap \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signal.o src/signal.cc

chromosome.o: src/GA/chromosome.cpp src/GA/chromosome.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QLine \
		../../.qt/5.1.1/gcc_64/include/QtCore/qline.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QPoint \
		../../.qt/5.1.1/gcc_64/include/QtCore/QDebug \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chromosome.o src/GA/chromosome.cpp

clossover.o: src/GA/clossover.cc src/GA/population.h \
		src/GA/individual.h \
		src/GA/chromosome.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QDebug \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clossover.o src/GA/clossover.cc

individual.o: src/GA/individual.cpp src/GA/individual.h \
		src/GA/chromosome.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o individual.o src/GA/individual.cpp

method.o: src/GA/method.cc src/GA/population.h \
		src/GA/individual.h \
		src/GA/chromosome.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QDebug \
		../../.qt/5.1.1/gcc_64/include/QtCore/qdebug.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qhash.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qchar.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpair.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtextstream.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiodevice.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstring.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbytearray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcoreevent.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmetatype.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qisenum.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qobject_impl.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlocale.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvariant.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qshareddata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qset.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o method.o src/GA/method.cc

mutate.o: src/GA/mutate.cc src/GA/population.h \
		src/GA/individual.h \
		src/GA/chromosome.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mutate.o src/GA/mutate.cc

population.o: src/GA/population.cc src/GA/population.h \
		src/GA/individual.h \
		src/GA/chromosome.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o population.o src/GA/population.cc

selectver3.05.o: src/GA/selectver3.05.cc src/GA/chromosome.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/QVector \
		../../.qt/5.1.1/gcc_64/include/QtCore/qvector.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qalgorithms.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobal.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qconfig.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qfeatures.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_power.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qmutex.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlogging.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qflags.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qtypetraits.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qsysinfo.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qiterator.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qlist.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qrefcount.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qarraydata.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qpoint.h \
		../../.qt/5.1.1/gcc_64/include/QtCore/qnamespace.h \
		src/GA/population.h \
		src/GA/individual.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selectver3.05.o src/GA/selectver3.05.cc

moc_draw.o: moc_draw.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_draw.o moc_draw.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

