######################################################################
# Automatically generated by qmake (3.0) ? 9? 21 18:47:28 2013
######################################################################

TEMPLATE = app
TARGET = simulator
INCLUDEPATH += . src src/GA
QT += widgets
QMAKE_CXXFLAGS += -std=gnu++11

# Input
HEADERS += src/car.h \
           src/draw.h \
           src/land.h \
           src/signal.h \
           src/GA/chromosome.h \
           src/GA/individual.h \
           src/GA/population.h
SOURCES += src/car.cc \
           src/draw.cc \
           src/land.cc \
           src/main.cc \
           src/navi.cc \
           src/signal.cc \
	   src/evaluate-01.cc \
           src/GA/chromosome.cpp \
           src/GA/clossover.cc \
           src/GA/individual.cpp \
           src/GA/method.cc \
           src/GA/mutate.cc \
           src/GA/population.cc \
           src/GA/selectver3.05.cc
